services:
  pg-bkp-restore-dev:
    container_name: pg-bkp-restore-dev
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    volumes:
      - pg-bkp-restore-dev-data:/files
    environment:
      # Production - Change acording to your environment
      - SRC_DB_HOST=my-database.com.br
      - SRC_DB_PORT=5435
      - SRC_DB_USER=postgres
      - SRC_DB_PASS=superPassword
      - SRC_DB_NAME=my-db
      # Destination - Change acording to your environment
      - DEST_DB_HOST=my-another-database.com.br
      - DEST_DB_PORT=5432
      - DEST_DB_USER=postgres
      - DEST_DB_PASS=superPassword
      - DEST_DB_NAME=my-another-db
      # Configuration
      - DO_BACKUP=1 # 1: true, 0: false - Do backup
      - DO_RESTORE=1 # 1: true, 0: false - Do restore

  pg-bkp-restore-prod:
    container_name: pg-bkp-restore-prod
    image: saulotarsobc/pg-bkp-restore:latest
    restart: no
    volumes:
      - pg-bkp-restore-prod-data:/files
    environment:
      # Production - Change acording to your environment
      - SRC_DB_HOST=my-database.com.br
      - SRC_DB_PORT=5435
      - SRC_DB_USER=postgres
      - SRC_DB_PASS=superPassword
      - SRC_DB_NAME=my-db
      # Destination - Change acording to your environment
      - DEST_DB_HOST=my-another-database.com.br
      - DEST_DB_PORT=5432
      - DEST_DB_USER=postgres
      - DEST_DB_PASS=superPassword
      - DEST_DB_NAME=my-another-db
      # Configuration
      - DO_BACKUP=1 # 1: true, 0: false - Do backup
      - DO_RESTORE=1 # 1: true, 0: false - Do restore

  pg-bkp-restore-db:
    container_name: pg-bkp-restore-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg-bkp-restore-db-data:/var/lib/postgresql/data

volumes:
  pg-bkp-restore-db-data:
    driver: local
  pg-bkp-restore-prod-data:
    driver: local
  pg-bkp-restore-dev-data:
    driver: local
